import Sidebar from './Sidebar'
import './globals.css'

export const metadata = {
  title: 'Wish Manager App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="font-sans">
        <main>
          <Sidebar />
          <div className="main-view-container">
            {children}
          </div>
        </main>
        </body>
    </html>
  )
}
